### ISSUE TITLE
Unable to add type "Service" in federation

### ISSUE THREAD

**Issue by josemarluedke** [99designs/gqlgen#1256]
I'm declaring a GraphQL type called "Service" in a federated gqlgen. gqlgen fails to generate because of "redeclared service type".

Reproduction: https://github.com/josemarluedke/gqlgen-fed-service-type
GraphQL: https://github.com/josemarluedke/gqlgen-fed-service-type/blob/master/graph/schema.graphqls

### What happened?
```
➜ go generate ./...
validation failed: packages.Load: /Users/josemarluedke/code/tmp/gqlgen-fed-service-type/graph/generated/generated.go:62:2: Service redeclared
/Users/josemarluedke/code/tmp/gqlgen-fed-service-type/graph/generated/generated.go:58:2: 	other declaration of Service
/Users/josemarluedke/code/tmp/gqlgen-fed-service-type/graph/generated/generated.go:135:27: e.complexity.Service.SDL undefined (type struct{ID func(childComplexity int) int} has no field or method SDL)
/Users/josemarluedke/code/tmp/gqlgen-fed-service-type/graph/generated/generated.go:139:31: e.complexity.Service.SDL undefined (type struct{ID func(childComplexity int) int} has no field or method SDL)
exit status 1
```

Here is the generated code: https://github.com/josemarluedke/gqlgen-fed-service-type/blob/master/graph/generated/generated.go#L58-L64

### What did you expect?

Only one type Service declared. No conflict with the Federation.

### Minimal graphql.schema and models to reproduce

Full repro: https://github.com/josemarluedke/gqlgen-fed-service-type
GraphQL: https://github.com/josemarluedke/gqlgen-fed-service-type/blob/master/graph/schema.graphqls

### versions
 - `gqlgen version` v0.11.3
 - `go version` 1.13.6
 - go modules

**Comment by frederikhors** [comment]
nope

**Comment by moensch** [comment]
I just hit the same thing - glad it got reported. The `ComplexityRoot` ends up with two child structs named `Service`.

One of them represents my actual model, the other looks like this:

```go
	Service struct {
		SDL func(childComplexity int) int
	}
```

**Comment by zhevron** [comment]
I just found this one as well when trying to migrate an existing schema to use federation, so renaming my type is hardly an option without causing breaking changes.

It seems to be caused by an internal model representing the service (as required by Apollo Federation) defined here: https://github.com/99designs/gqlgen/blob/master/plugin/federation/fedruntime/runtime.go#L6

This is currently a blocker for us, so I'll take a stab at solving it in a way that works for us. If anyone has any bright ideas as to how this can be fixed without renaming the internal struct, I'm open to suggestions.

**Comment by moensch** [comment]
> It seems to be caused by an internal model representing the service (as required by Apollo Federation) defined here: https://github.com/99designs/gqlgen/blob/master/plugin/federation/fedruntime/runtime.go#L6

@zhevron I took a look at this too and believe it's a limitation in this function here: https://github.com/99designs/gqlgen/blob/997da421b0b80884fcb43c8c6a22d747564b301c/codegen/templates/templates.go#L285-L306

The actual schema type is `_service`, but this function, when converting schema types to Go types, essentially ignores underscores.

I started an attempt to fix it by doing something as simple as this - but soon got stuck five layers deep in templates and code generation with no way out :-/

```golang
if strings.HasPrefix(name, "_") {
  return fmt.Sprintf("Underscore%s", string(runes))
}
```

**Comment by zhevron** [comment]
@moensch You are absolutely correct that this is what causes it. We had our own entities named `Entity` and `Service` which in turn caused the problem. Just like you, I looked into the issue and found no real way but to mess with the templating.

This is how I fixed it for us, but YMMV: https://github.com/zhevron/gqlgen/commit/cecd727168a6a5873c2d5ac4d75a857da341dbe7

In short, I renamed the gqlgen `Entity` to `FederatedEntity` and `Service` to `FederatedService`. This also requires your user code to reference the `FederatedEntity` interface instead of the `Entity` interface, so it is a breaking change to the API.
The breaking change is also why I'm hesitant to push this back as a change. I'd like to find a way to solve this without causing any real API changes.

**Comment by moensch** [comment]
I hear you. We are at a point where we could very easily still absorb upstream API changes. I would suggest you throw the PR out there and start gathering feedback - it looks eerily similar to what I've come up with so far.

I also tried looking at the code surrounding "complexity" to see why this is smashing types from different packages into the same "namespace". This seemed wrong to me, and is one of probably two places a fix could help avoid the need to rename this Go type.

**Comment by zhevron** [comment]
I'll take one last pass at the solution to see if I can at least move the "logic" of the change out of the core `codegen` package and into the federation plugin package. Seems weird to have a plugin halfway implemented in core. Hopefully I'll have something in the next couple of days or sooner, depending on my workload.

**Comment by AndrewRayCode** [comment]
Our team just hit this as well. We have a type named `Service` in the graph. Changing the name isn't an option because it's a value type used in other subgraphs and we have to match it identically.

I'm confused why something like this doesn't work:

in `gqlgen.yml`
```
  Service:
    model: app/model.ServiceTest
```

This seems to be handled fine by gqlgen, but the error still happens, and the duplicate `Service` struct gets put in the `ComplexityRoot` struct.

**Comment by AndrewRayCode** [comment]
@zhevron sorry for double ping, I mostly copy-pasta'd your work into a PR. It's what we're attempting in our own fork for now, so either way thanks for the code.

**Comment by zhevron** [comment]
@AndrewRayCode No worries at all. I'm glad you could take the time to make this. I've been absolutely swamped since the last update and will be for the foreseeable future. Turns out it's hard to get the time to address this when your workaround fork is working just fine.
