### ISSUE TITLE
package github.com/99designs/gqlgen: no Go files in

### ISSUE THREAD

**Issue by coderste** [99designs/gqlgen#800]
### What happened?

When running `go mod vendor` and then adding `//go:generate go run -mod=vendor github.com/99designs/gqlgen` to the top of my `resolver.go` file when I try and run `go generate -mod=vendor ./...` I get the following error
> package github.com/99designs/gqlgen: no Go files in /Users/shi03/code/projects/gs/common-api/vendor/github.com/99designs/gqlgen

### What did you expect?

I expected the `go generate -mod=vendor ./...` to re-generate the gql generated files.

### versions
 - `gqlgen version`? v0.9.1
 - `go version`? go version go1.12.6 darwin/amd64
 - dep or go modules? go modules

Unsure if this is an error on my end. But because I vendor all my dependancies when running any Go commands I add the `-mod=vendor` flag[1] to every command so that Go using the dependancies inside the vendor folder rather than the cache/downloading them.

[1] - https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

**Comment by vektah** [comment]
go run behaves a bit weird in vendor mode, I wrote [gorunpkg](https://github.com/vektah/gorunpkg) to work around this behaviour. I haven't updated it to packages yet but if your still censoring it might just work? 

There's a few more details on how to use it in the dep getting started guide 
https://gqlgen.com/getting-started-dep/

**Comment by coderste** [comment]
I've tried install `gorunpkg` and adding `//go:generate gorunpkg github.com/99designs/gqlgen` to the top of my file.

Unfortunately I still get the same error:
> pkg: go/build: importGo github.com/99designs/gqlgen: exit status 1
can't load package: package github.com/99designs/gqlgen: no Go files in /code/project/vendor/github.com/99designs/gqlgen

I've opened an issue on the Go repo https://github.com/golang/go/issues/33240 to see what they recommend.

As this isn't an issue with the gqlgen package I'm happy for you to close this issue :)

**Comment by bugzpodder** [comment]
i've been using gohack, not sure if it would work for you

**Comment by coderste** [comment]
So just thought I'd come back and post the solution to this.

Based on information from https://github.com/golang/go/issues/29516 what we can is the following:

Create a `gqlgen` inside a `scripts` folder and add the following code
```
// +build tools

package main

import "github.com/99designs/gqlgen/cmd"

func main() {
	cmd.Execute()
}
```

Instead of using `// +build ignore` we use `// +build tools` because `build ignore` will not work when trying to vendor dependancies. For example having `build ignore` will leave out the `cmd` folder of the `99designs/gqlgen` package. What `build tools` does instead is pull in the dependancies into the `vendor` directory but will still ignore them `dependancies` when running `go build`.

Then inside the `resolver.go` file we can just have

```
//go:generate go run ../../scripts/gqlgen.go
```

This will then have `go generate` to work with `vendor`ed modules

**Comment by akhiljain23** [comment]
As a workaround I did `rm -rf vendor` then ran `go run github.com/99designs/gqlgen generate` and then vendor again

**Comment by khanakia** [comment]
Very simple solution you do not have to do anything.

Just edit your main.go and import the package like this
```import _ "github.com/99designs/gqlgen"```

Then run these commands
```
go mod vendor
go run github.com/99designs/gqlgen generate
```

**Comment by leandroruel** [comment]
jesus no matter what i do none of this solutions works for me, i'm already feeling dumb.

**Comment by khanakia** [comment]
@leandroruel just follow this tutorial https://gqlgen.com/getting-started/
This will work 100%

**Comment by leandroruel** [comment]
thanks @khanakia now i fixed it. \o/

**Comment by khanakia** [comment]
@leandroruel how exactly did you fix this ? Can you leave some information here so it will be helpful for other users in case they face the same issue in future.

**Comment by khanakia** [comment]
**HERE's THE SOLUTION:**

create a new file called `gqlgen.go` and place this code
```
// +build tools

package main

import (
	"fmt"

	"github.com/99designs/gqlgen/cmd"
)

func main() {
	fmt.Println("Building Graphql schema")
	cmd.Execute()
}
```

now run this commands
```
go mod vendor
go run ./gqlgen.go
```

OR you can used the command as generator by placing this code in your main.go
```
//go:generate go run ./gqlgen.go
```

after that you can simply run `go generate` command

**Comment by renxinhe** [comment]
I'm running into the same issue here. After trying the solution, I'm getting the following error:
```
$ go run ./gqlgen.go
gqlgen.go:9:2: no required module provides package github.com/99designs/gqlgen/cmd; to add it:
        go get github.com/99designs/gqlgen/cmd

$ go get github.com/99designs/gqlgen/cmd
go: module github.com/99designs/gqlgen@upgrade found (v0.17.22), but does not contain package github.com/99designs/gqlgen/cmd
```

My go.mod is showing gqlgen version `v0.17.22`. After looking at the current source code, I don't think the "cmd/" directory still exists. Does anyone know a to date solution to resolve this "no Go files" circular dependency issue between `go mod tidy` and `go generate ./...`?

**Comment by somatom98** [comment]
@renxinhe executing `go get github.com/99designs/gqlgen@v0.17.40`  did it for me
